create database customer_behavior
select * from customer limit 20;
USE customer_behavior;

-- Q1 what is the total reveneue generated by male vs female cutomers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- Q2. which customers used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

select * from customer

-- Q3. which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. compare the average purchase amount between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5 Do the subescribed customers spend more? compare average spend and the total revenue between supescribers and non supscribers
SELECT 
    subscription_status, 
    round(AVG(purchase_amount), 2) AS avg_spend,
    COUNT(customer_id) AS total_customers,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM 
    customer
GROUP BY 
    subscription_status
ORDER BY 
    total_revenue DESC, 
    avg_spend DESC;
    
    -- Q6 which 5 products have the highest percentage of purchases with discounts applied?
    select item_purchased,
    round(sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
    from customer
    group by item_purchased
    order by discount_rate desc
    limit 5;
    
    -- Q7. segment customers into new, returnung and loyal based on their total
    with customer_type as (
    select customer_id ,previous_purchases,
    case
		when previous_purchases = 1 then 'new'
        when previous_purchases between 2 and 10 then 'returning'
        else 'loyal'
        end as customer_segment
	from customer
    )
    
select customer_segment , count(*) as "number of customers"
from customer_type
group by customer_segment

select * from customer

-- Q8. what are the top 3 most purchased products within each category
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc)as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as repeat_buyers , subscription_status
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. what is the revenue contribution of each age group?
select sum(purchase_amount) as total_revenue,
age_group
from customer
group by age_group 
order by total_revenue desc;
